### ISSUE TITLE
UX for removing applications

### ISSUE THREAD

**Issue by slemrmartin** [RedHatInsights/sources-ui#167]
Hi @terezanovotna, there is one confusing behaviour when managing applications in Sources. 
When I remove one or more applications, then I must click to "Cancel" link. 
It can be taken that my changes will be reverted.

**Comment by rvsia** [comment]
@slemrmartin @terezanovotna What about to change `Cancel` to `Close`?

**Comment by slemrmartin** [comment]
:+1: sounds good

**Comment by rvsia** [comment]
This is pretty old issue - the UX for removing apps has been already redesigned, so I am closing this. Feel free to re-open, if you find any issues.
