### ISSUE TITLE
Update Cost Management AWS wizard to use new cost-sources API

### ISSUE THREAD

**Issue by dccurtis** [RedHatInsights/sources-ui#188]
New cost management Sources API was added with https://github.com/project-koku/koku/pull/1481.

Please move the AWS bucket API calls to use the new API.

Once done we can merge https://github.com/project-koku/koku/pull/1548 to remove the old APIs.

**Comment by rvsia** [comment]
Closed by RedHatInsights/frontend-components#294 and #195

**Comment by dccurtis** [comment]
@rvsia looks like these changes are for azure. Is the aws bucket also converted by one of these?

**Comment by rvsia** [comment]
Yeah, It is the same function.
