### ISSUE TITLE
Source removal warning for destroying application data

### ISSUE THREAD

**Issue by dccurtis** [RedHatInsights/sources-ui#335]
For Cost Management, we are removing all data when the application is removed from the source.  The in CI-beta the warning for removing data is happening after the source is destroyed, not the application.  At this point it's too and the user just removed their cost-mgmt data before getting warned.

There is future work being discussed around implementing a cost management "soft delete" feature with a data retention policy.  That will certainly have implications to this UX (@nlcwong).

For now I wanted to call it out that this warning message should be occurring before the application is removed, not the source with today's cost-platform sources integration.

1. Delete Source with application attached
![drop_down_delete](https://user-images.githubusercontent.com/4523309/81004183-0442c500-8e1a-11ea-865e-2fa4e0743896.png)

2. Warning message that an application is attached to the source.  Gives opportunity to remove.
![remove_app_from_source](https://user-images.githubusercontent.com/4523309/81004242-10c71d80-8e1a-11ea-81b2-f6f95ea80eb8.png)

3. Clicks Remove for confirmation box (no warning message yet...).  Cost data is removed when the Red Remove button is clicked.
![remove_app_confirm](https://user-images.githubusercontent.com/4523309/81004271-21779380-8e1a-11ea-9589-b0b7233556dd.png)

4. Remove source confirmation now that all applications are gone.  (Cost Management data is already gone at this point)
![app_gone_data_destroy_msg](https://user-images.githubusercontent.com/4523309/81004355-453ad980-8e1a-11ea-8792-b91103a8be4b.png)

**Comment by rvsia** [comment]
cc @syncrou @gtanzillo

**Comment by rvsia** [comment]
Yeah, there should have been a warning text when removing applications (the application removal modal is basically a placeholder), but we have actually never got the UX to finish that - each application should have had its own removal text - never got the texts or a place where to store these texts in the DB. I don't know what is the current plan for that or who does the UX.

**Comment by nlcwong** [comment]
The platform UX team has started engaging with the various apps on this subject. 
 Including them to this conversation: @RedHatInsights/platform-experience-ux

**Comment by rvsia** [comment]
@dccurtis The remove modal was updated in https://github.com/RedHatInsights/sources-ui/pull/345 Can you take a look on it in the CI?

**Comment by dccurtis** [comment]
@rvsia Looks great! Thanks for doing that.  Really like how it removes the application and source with proper warning in one step. 👍

**Comment by rvsia** [comment]
Yeah, I have never liked the fact users have to click multiple times to remove one source... so, can we close this issue? :)

**Comment by dccurtis** [comment]
Yeah, lets close it, thanks
